### ISSUE TITLE
USER STORY: Booking a class

### ISSUE THREAD

**Issue by s-batish** [s-batish/tango-tennis#1]
### EPIC: Booking Classes

***

### USER STORY
As a ***registered user***, I want to ***be able to book a class***, so that I can ***be added to the tennis lesson***

***

### ACCEPTANCE CRITERIA

- [x] User is able to successfully book their tennis class through the form on the booking page
- [x] Validation errors will be presented to user for any invalid inputs or unavailable dates/times

***

### TASKS
- [x] Create booking page
- [x] Create booking form to have a dropdown option for the level (beginner, intermediate, advanced), a datepicker, and time options
- [x] Ensure validation errors will appear for any invalid inputs
- [x] Customise styling
- [x] Test functionality
