### ISSUE TITLE
USER STORY: Delete account

### ISSUE THREAD

**Issue by s-batish** [s-batish/tango-tennis#10]
### EPIC: Registration and User Accounts

***

### USER STORY
As a ***registered user***, I want to ***be able to delete my account***, if I no longer want to be signed up to Tango Tennis

***

### ACCEPTANCE CRITERIA
- [ ] User is able to delete their account through their account profile
- [ ] Notification to appear to confirm user's action before being deleted

***

### TASKS
- [ ] On user profile page, add delete account button and functionality to 'My Profile' section
- [ ] Customise styling
- [ ] Test functionality
