### ISSUE TITLE
USER STORY: Clear navbar and footer

### ISSUE THREAD

**Issue by s-batish** [s-batish/tango-tennis#11]
### EPIC: Viewing the features of Tango Tennis

***

### USER STORY
As a ***general user***, I want to ***see a clearly structured navbar and footer***, so that I can ***see what will be featured on the site and can access Tango Tennis' social media links easily***

***

### ACCEPTANCE CRITERIA
- [x] Navbar to make the site easy to navigate
- [x] Logo in top left corner of each page which functions as a home button
- [x] Footer with social media links

***

### TASKS
- [x] Create logo
- [x] Create navbar
- [x] Create footer with social media links
- [x] Create base template to be featured on all pages
- [x] Test functionality
