### ISSUE TITLE
USER STORY: Responsive website

### ISSUE THREAD

**Issue by s-batish** [s-batish/tango-tennis#12]
### EPIC: Viewing the features of Tango Tennis

***

### USER STORY
As a ***general user***, I want ***the website to be responsive***, so that I can ***access it on a range of devices***
***

### ACCEPTANCE CRITERIA
- [x] Website needs to be created with responsive design starting at 320px for mobiles, tablets and desktops

***

### TASKS
- [x] Create media queries starting with mobile first
- [x] Create hamburger navbar for mobile and tablet devices
- [x] Customise styling
- [x] Test functionality
