### ISSUE TITLE
USER STORY: About information

### ISSUE THREAD

**Issue by s-batish** [s-batish/tango-tennis#13]
### EPIC: Viewing the features of Tango Tennis

***

### USER STORY
As a ***general user***, I want to ***see clearly laid out information about Tango Tennis***, so that I can ***see what they have to offer***

***

### ACCEPTANCE CRITERIA
- [x] Information about Tango Tennis detailing what they do, who they cater for, and what classes people can sign up for

***

### TASKS
- [x] Create an 'About' section on the home page
- [x] Create a page detailing the different levels
- [x] Create timetables for the different classes
- [x] Customise styling
