### ISSUE TITLE
USER STORY: Leaving a review

### ISSUE THREAD

**Issue by s-batish** [s-batish/tango-tennis#17]
### EPIC: Reviewing classes

***

### USER STORY
As a ***registered user***, I want to ***be able to review my classes***, so that I can ***give feedback***

***

### ACCEPTANCE CRITERIA
- [x] Signed in users can leave reviews for the classes/coaches

***

### TASKS
- [x] Create a comments feature on home page below about info
- [x] Ensure only signed in users can leave reviews
- [x] Test functionality
