### ISSUE TITLE
USER STORY: Creating lessons

### ISSUE THREAD

**Issue by s-batish** [s-batish/tango-tennis#19]
### EPIC: Administrative managing of classes

***

### USER STORY
As an ***admin member***, I want to ***create tennis lessons for the different levels***, so that I can ***provide a clear timetable of our classes***

***

### ACCEPTANCE CRITERIA
- [x] Beginner, intermediate and advanced lesson timetables to be created
- [x] Only to be created by admin users
***

### TASKS
- [x] Create admin panel functionality for updating class timetables
- [x] Create model to create classes
- [x] Include the three different levels
- [x] Create view and template to see lessons
- [x] Test functionality
