### ISSUE TITLE
USER STORY: Edit lessons (admin)

### ISSUE THREAD

**Issue by s-batish** [s-batish/tango-tennis#20]
### EPIC: Administrative managing of classes

***

### USER STORY
As an ***admin member***, I want to ***be able to edit the lesson timetables***, so that I can ***update them as necessary***

***

### ACCEPTANCE CRITERIA
- [x] Beginner, intermediate and advanced lesson timetables to have the ability to be updated as necessary
- [x] Only to be edited by admin members

***

### TASKS
- [x] Create edit button on our_classes template
- [x] Create edit classes page
- [x] Test functionality
