### ISSUE TITLE
USER STORY: Delete lessons (admin)

### ISSUE THREAD

**Issue by s-batish** [s-batish/tango-tennis#21]
### EPIC: Administrative managing of classes

***

### USER STORY
As an ***admin member***, I want to ***be able to delete lessons***, so that I can ***they do not appear in the timetable when the timetable needs to change***

***

### ACCEPTANCE CRITERIA
- [x] Beginner, intermediate and advanced lessons to have the ability to be deleted from their timetable as necessary
- [x] Only to be edited by admin members

***

### TASKS
- [x] Create delete button on our_classes template
- [x] Create delete classes page
- [x] Test functionality
