### ISSUE TITLE
USER STORY: Sign up page

### ISSUE THREAD

**Issue by s-batish** [s-batish/tango-tennis#6]
### EPIC: Registration and User Accounts

***

### USER STORY
As a ***new user***, I want to ***navigate to the sign up page***, so that I can ***create an account***
***

### ACCEPTANCE CRITERIA
- [x] User is able to create an account
- [x] Validation errors will be presented to user for any invalid inputs
- [x] UX is visually appealing
***

### TASKS
- [x] Implement sign up form and functionality using allauth
- [x] Customise styling
- [x] Test functionality
