### ISSUE TITLE
USER STORY: Login to account

### ISSUE THREAD

**Issue by s-batish** [s-batish/tango-tennis#7]
### EPIC: Registration and User Accounts

***

### USER STORY
As a ***registered user***, I want to ***login to my account***, so that I can ***make and update bookings***

***

### ACCEPTANCE CRITERIA
- [x] User is able to sign in to their account. 
- [x] UX is visually appealing
***

### TASKS
- [x] Implement login form and functionality using allauth
- [x] Customise styling
- [x] Test functionality
