### ISSUE TITLE
USER STORY: Log out of account

### ISSUE THREAD

**Issue by s-batish** [s-batish/tango-tennis#8]
### EPIC: Registration and User Accounts

***

### USER STORY
As a ***registered user***, I want to ***log out of my account***, so that I can ***protect my information from being accessed by others***
***

### ACCEPTANCE CRITERIA
- [x] User is able to sign out of their account
- [x] UX is visually appealing
***

### TASKS
- [x] Implement log out form and functionality using allauth
- [x] Customise styling
- [x] Test functionality
